// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/mcv0000/storeflow-api/internal/user"
)

type AuthPayload struct {
	Token string     `json:"token"`
	User  *user.User `json:"user"`
}

type CreateOrderInput struct {
	StoreID       string                  `json:"storeId"`
	CustomerEmail string                  `json:"customerEmail"`
	Items         []*CreateOrderItemInput `json:"items"`
}

type CreateOrderItemInput struct {
	ProductID string `json:"productId"`
	Quantity  int    `json:"quantity"`
}

type CreateProductInput struct {
	StoreID        string  `json:"storeId"`
	Name           string  `json:"name"`
	Description    *string `json:"description,omitempty"`
	PriceCents     int     `json:"priceCents"`
	Currency       *string `json:"currency,omitempty"`
	InventoryCount *int    `json:"inventoryCount,omitempty"`
}

type CreateStoreInput struct {
	Name string  `json:"name"`
	Slug *string `json:"slug,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}
