package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/mcv0000/storeflow-api/internal/auth"
	orderdomain "github.com/mcv0000/storeflow-api/internal/order"
	"github.com/mcv0000/storeflow-api/internal/product"
	"github.com/mcv0000/storeflow-api/internal/store"
	"github.com/mcv0000/storeflow-api/internal/user"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input RegisterInput) (*AuthPayload, error) {
	domainUser, token, err := r.userService.Register(ctx, input.Email, input.Password, input.Name)
	if err != nil {
		return nil, err
	}

	return &AuthPayload{
		Token: token,
		User:  domainUser,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input LoginInput) (*AuthPayload, error) {
	domainUser, token, err := r.userService.Login(ctx, input.Email, input.Password)
	if err != nil {
		return nil, err
	}

	return &AuthPayload{
		Token: token,
		User:  domainUser,
	}, nil
}

// CreateStore is the resolver for the createStore field.
func (r *mutationResolver) CreateStore(ctx context.Context, input CreateStoreInput) (*store.Store, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	slug := ""
	if input.Slug != nil {
		slug = *input.Slug
	}

	return r.storeService.Create(ctx, userID, input.Name, slug)
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input CreateProductInput) (*product.Product, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	currency := "USD"
	if input.Currency != nil {
		currency = *input.Currency
	}

	inventoryCount := 0
	if input.InventoryCount != nil {
		inventoryCount = *input.InventoryCount
	}

	return r.productService.Create(ctx, userID, input.StoreID, input.Name, input.Description, input.PriceCents, currency, inventoryCount)
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input CreateOrderInput) (*orderdomain.Order, error) {
	items := make([]orderdomain.CreateItemParams, 0, len(input.Items))
	for _, item := range input.Items {
		items = append(items, orderdomain.CreateItemParams{
			ProductID: item.ProductID,
			Quantity:  item.Quantity,
		})
	}

	return r.orderService.Create(ctx, orderdomain.CreateParams{
		StoreID:       input.StoreID,
		CustomerEmail: input.CustomerEmail,
		Items:         items,
	})
}

// UpdateOrderStatus is the resolver for the updateOrderStatus field.
func (r *mutationResolver) UpdateOrderStatus(ctx context.Context, id string, status orderdomain.Status) (*orderdomain.Order, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	return r.orderService.UpdateStatus(ctx, userID, id, status)
}

// CreatedAt is the resolver for the createdAt field.
func (r *orderResolver) CreatedAt(ctx context.Context, obj *orderdomain.Order) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *orderResolver) UpdatedAt(ctx context.Context, obj *orderdomain.Order) (string, error) {
	return obj.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *orderItemResolver) CreatedAt(ctx context.Context, obj *orderdomain.OrderItem) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *productResolver) CreatedAt(ctx context.Context, obj *product.Product) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *productResolver) UpdatedAt(ctx context.Context, obj *product.Product) (string, error) {
	return obj.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*user.User, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	return r.userService.GetByID(ctx, userID)
}

// MyStores is the resolver for the myStores field.
func (r *queryResolver) MyStores(ctx context.Context) ([]*store.Store, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	return r.storeService.GetByOwnerID(ctx, userID)
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, storeID string, activeOnly *bool) ([]*product.Product, error) {
	active := false
	if activeOnly != nil {
		active = *activeOnly
	}

	return r.productService.GetByStoreID(ctx, storeID, active)
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*orderdomain.Order, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	return r.orderService.GetByID(ctx, userID, id)
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, storeID string, status *orderdomain.Status) ([]*orderdomain.Order, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	return r.orderService.GetByStoreID(ctx, userID, storeID, status)
}

// CreatedAt is the resolver for the createdAt field.
func (r *storeResolver) CreatedAt(ctx context.Context, obj *store.Store) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *storeResolver) UpdatedAt(ctx context.Context, obj *store.Store) (string, error) {
	return obj.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *user.User) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *user.User) (string, error) {
	return obj.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

// OrderItem returns OrderItemResolver implementation.
func (r *Resolver) OrderItem() OrderItemResolver { return &orderItemResolver{r} }

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Store returns StoreResolver implementation.
func (r *Resolver) Store() StoreResolver { return &storeResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type orderResolver struct{ *Resolver }
type orderItemResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type storeResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
